BEGIN TRANSACTION;

ALTER TABLE Orders ADD COLUMN Address TEXT NOT NULL DEFAULT 'empty';

CREATE TABLE IF NOT EXISTS AddressTracker (
	AddressTrackerID	INTEGER PRIMARY KEY,
	CoinType	TEXT NOT NULL UNIQUE,
	LastIndex	INTEGER NOT NULL
);

COMMIT;
